### PR TITLE
Move ConvertCUDNNToRuntime implementation to transforms

### PR DESCRIPTION
**Pull request by frgossen**

### CODE REVIEW

**Comment by ezhulenev** [comment]
I was actually following IREE style (e.g. https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/Dialect/VMVX), to keep conversions (populateXYZ) separate from passes that compose these conversions into "units of work", and `cudnn` to `func` seems to be a "conversion" in MLIR terminology

**Comment by ezhulenev** [comment]
The rule of thumb is that if you use ConversionPatternRewrite, it should go under conversions, otherwise it can go under transforms, though all passes always defined under transforms for some reason

**Comment by frgossen** [comment]
Ah, interesting. Yes, I thought both, conversion and transform make sense in this case, just found it strange that this would be separated in two files. Is that a conscious decision in IREE? 
Also, probably not the most important thing.

**Comment by ezhulenev** [comment]
Not sure, but vmvx is the newest dialect and I assume it has all “best practices” in it, so I just followed it

**Pull request closed without merging**
